### ISSUE TITLE
Where does paperboy search for podcasts?

### ISSUE THREAD

**Issue by bonelifer** [ccozkan/podcasts.paperboy.digital#140]
Where does paperboy search for podcasts?

**Comment by ccozkan** [comment]
it searches on itunes by sending request to `https://itunes.apple.com/search?term=#{@query}&media=podcast`. and this happens at https://github.com/ccozkan/podcasts.paperboy.digital/blob/master/app/services/feed_searcher_service.rb :)

**Comment by ccozkan** [comment]
it searches on itunes by sending request to `https://itunes.apple.com/search?term=#{@query}&media=podcast`. and this happens at https://github.com/ccozkan/podcasts.paperboy.digital/blob/master/app/services/feed_searcher_service.rb :)
